# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ticket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket'),
            preserve_default=False,
        ),
    ]
