# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_item_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='place',
            field=models.TextField(default=b'Brak'),
        ),
    ]
