# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.Category'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='serial',
            field=models.CharField(default=b'Brak', max_length=50),
        ),
    ]
