# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20160310_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(),
        ),
    ]
