# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20160310_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='brak', max_length=100),
            preserve_default=False,
        ),
    ]
