# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20160310_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='singleCost',
            field=models.FloatField(default=0),
        ),
    ]
